In [57]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Name of the CSV file
file = '../ignore/US_Accidents_May19.csv'
df = pd.read_csv(file)

#Source: https://www.fhwa.dot.gov/policyinformation/statistics/2017/
dl_file = '../ignore/US_DLCount.csv'
df_dlbystate = pd.read_csv(dl_file)

In [59]:
df.head()
# df_dlbystate.head()
# df.count()

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,MapQuest,201.0,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,MapQuest,201.0,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,MapQuest,201.0,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,MapQuest,201.0,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,MapQuest,201.0,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,...,False,False,False,False,True,False,Day,Day,Day,Day

In [16]:
#Create Relevant DataFrame
df_location = df[["ID", "Severity", "Start_Time", 
#                   "End_Time",  "Distance(mi)",
                  "City", "County", "State", "Timezone"]]
df_location.head()
# df_location.count()

,ID,Severity,Start_Time,City,County,State,Timezone
0,A-1,3,2016-02-08 05:46:00,Dayton,Montgomery,OH,US/Eastern
1,A-2,2,2016-02-08 06:07:59,Reynoldsburg,Franklin,OH,US/Eastern
2,A-3,2,2016-02-08 06:49:27,Williamsburg,Clermont,OH,US/Eastern
3,A-4,3,2016-02-08 07:23:34,Dayton,Montgomery,OH,US/Eastern
4,A-5,2,2016-02-08 07:39:07,Dayton,Montgomery,OH,US/Eastern

In [17]:
#Recategorize the timestamp - year, month, time categories
df_location["Start_Year"] = df_location["Start_Time"].agg(lambda x: x.split("-")[0])
df_location["Start_Month"] = df_location["Start_Time"].agg(lambda x: x.split("-")[1])
df_location["Start_HrMin"] = df_location["Start_Time"].agg(lambda x: x.split()[1])
df_location["Start_Hr"] = df_location["Start_HrMin"].agg(lambda x: x.split(":")[0])
dfcl_location = df_location [["ID", "Severity", 
                              "Start_Year", "Start_Month", "Start_Hr",
                              "City", "County", "State", "Timezone"]]
dfcl_location.head()

C:\Users\heain\AppData\Local\Continuum\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\heain\AppData\Local\Continuum\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\heain\AppData\Local\Continuum\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\heain\AppData\Local\Continuum\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

,ID,Severity,Start_Year,Start_Month,Start_Hr,City,County,State,Timezone
0,A-1,3,2016,02,05,Dayton,Montgomery,OH,US/Eastern
1,A-2,2,2016,02,06,Reynoldsburg,Franklin,OH,US/Eastern
2,A-3,2,2016,02,06,Williamsburg,Clermont,OH,US/Eastern
3,A-4,3,2016,02,07,Dayton,Montgomery,OH,US/Eastern
4,A-5,2,2016,02,07,Dayton,Montgomery,OH,US/Eastern

In [52]:
dfcl_location["Start_Year"].value_counts().sort_values()
# dfcl_location["Start_Month"].value_counts().sort_values()
# dfcl_location["Start_Hr"].value_counts().sort_values()
# dfcl_location.dtypes

2015         1
2019    223223
2016    410601
2017    717490
2018    892624
Name: Start_Year, dtype: int64

In [ ]:
#Groupbys, new data frames
#Visualize - https://towardsdatascience.com/a-complete-guide-to-an-interactive-geographical-map-using-python-f4c5197e23e0

In [ ]:
# IDThis is a unique identifier of the accident record.
# SourceIndicates source of the accident report (i.e. the API which reported the accident.).
# TMCA traffic accident may have a Traffic Message Channel (TMC) code which provides more detailed description of the event.
# SeverityShows the severity of the accident, a number between 1 and 4, where 1 indicates the least impact on traffic (i.e., short delay as a result of the accident) and 4 indicates a significant impact on traffic (i.e., long delay).
# Start_Time Shows start time of the accident in local time zone.
# End_Time Shows end time of the accident in local time zone.
# Start_LatShows latitude in GPS coordinate of the start point.
# Start_LngShows longitude in GPS coordinate of the start point.
# End_LatShows latitude in GPS coordinate of the end point.
# End_LngShows longitude in GPS coordinate of the end point.
# Distance(mi)The length of the road extent affected by the accident.
# DescriptionShows natural language description of the accident.
# NumberShows the street number in address field.
# StreetShows the street name in address field.
# SideShows the relative side of the street (Right/Left) in address field.
# CityShows the city in address field.
# CountyShows the county in address field.
# StateShows the state in address field.
# ZipcodeShows the zipcode in address field.
# CountryShows the country in address field.
# TimezoneShows timezone based on the location of the accident (eastern, central, etc.).
# Airport_CodeDenotes an airport-based weather station which is the closest one to location of the accident.
# Weather_TimestampShows the time-stamp of weather observation record (in local time).
# Temperature(F)Shows the temperature (in Fahrenheit).
# Wind_Chill(F)Shows the wind chill (in Fahrenheit).
# Humidity(%)Shows the humidity (in percentage).
# Pressure(in)Shows the air pressure (in inches).
# Visibility(mi)Shows visibility (in miles).
# Wind_DirectionShows wind direction.
# Wind_Speed(mph)Shows wind speed (in miles per hour).
# Precipitation(in)Shows precipitation amount in inches, if there is any.
# Weather_ConditionShows the weather condition (rain, snow, thunderstorm, fog, etc.)
# AmenityA POI annotation which indicates presence of amenity in a nearby location.
# BumpA POI annotation which indicates presence of speed bump or hump in a nearby location.
# CrossingA POI annotation which indicates presence of crossing in a nearby location.
# Give_WayA POI annotation which indicates presence of give_way in a nearby location.
# JunctionA POI annotation which indicates presence of junction in a nearby location.
# No_ExitA POI annotation which indicates presence of no_exit in a nearby location.
# RailwayA POI annotation which indicates presence of railway in a nearby location.
# RoundaboutA POI annotation which indicates presence of roundabout in a nearby location.
# StationA POI annotation which indicates presence of station in a nearby location.
# StopA POI annotation which indicates presence of stop in a nearby location.
# Traffic_CalmingA POI annotation which indicates presence of traffic_calming in a nearby location.
# Traffic_SignalA POI annotation which indicates presence of traffic_signal in a nearby location.
# Turning_LoopA POI annotation which indicates presence of turning_loop in a nearby location.
# Sunrise_SunsetShows the period of day (i.e. day or night) based on sunrise/sunset.
# Civil_TwilightShows the period of day (i.e. day or night) based on civil twilight.
# Nautical_TwilightShows the period of day (i.e. day or night) based on nautical twilight.
# Astronomical_TwilightShows the period of day (i.e. day or night) based on astronomical twilight.